ipAddr: 192.168.56.10

server:
  port: 9001

spring:
  application:
    name: gulimall-order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${ipAddr}:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  session: # Use redis to store session
    store-type: redis
  redis:
    host: ${ipAddr}
  rabbitmq:
    host: ${ipAddr}
    port: 5672
    # Specify virtual host
    virtual-host: /
    username: guest
    password: guest
    # Publisher confirm and return configuration
    publisher-confirms: true
    # Publisher returns configuration for message routing failures
    publisher-returns: true
    # When routing fails, return callback to producer
    template:
      mandatory: true
    # Manual ack messages to prevent message loss
    listener:
      simple:
        acknowledge-mode: manual
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  zipkin:
    base-url: ${ipAddr}:9411/
    # Close auto discovery to prevent conflicts
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


#my-rabbit-config:
#  stock:
#    exchange:
#    delayQueue:
#    delayRoutingKey:
#    releaseQueue:
#    releaseRoutingKey: stock.release
#    # Lock timeout in milliseconds
#    ttl:

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

alipay:
  app_id: 2016102100732649
  # Alipay asynchronous callback notification
  notify_url: http://sthwsr.natappfree.cc/payed/notify
  return_url: http://member.gulimall.com/memberOrder.html
  timeout: 15m
